const $=s=>document.querySelector(s);
const fields=['businessName','tagline','description','whatsapp','city','address','aboutTitle','aboutText','ctaTitle','product1','product2','product3','brandColor','logo','heroImage','productImage1','productImage2','productImage3'];
const templateNames={tpl_umkm_modern:'UMKM Modern',tpl_umkm_katalog:'UMKM Katalog'};
const packageNames={starter:'Starter',growth:'Growth',business:'Business',pro:'Pro'};
let selectedPackage=localStorage.getItem('webumkm_package')||'starter';
let selectedTemplate=localStorage.getItem('webumkm_template')||'tpl_umkm_modern';
function slugify(value){return value.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'website-umkm';}
function currentSlug(){return localStorage.getItem('webumkm_site_slug')||slugify($('#businessName').value);}
function content(){return{aboutTitle:$('#aboutTitle').value,aboutText:$('#aboutText').value,ctaTitle:$('#ctaTitle').value,brandColor:$('#brandColor').value,logo:$('#logo').value.trim(),heroImage:$('#heroImage').value.trim(),products:[$('#product1').value,$('#product2').value,$('#product3').value],productImages:[$('#productImage1').value.trim(),$('#productImage2').value.trim(),$('#productImage3').value.trim()]};}
function sync(){ $('#pName').textContent=$('#businessName').value; $('#pTagline').textContent=$('#tagline').value; $('#pDescription').textContent=$('#description').value; $('#selectedTemplateLabel').textContent=templateNames[selectedTemplate]||selectedTemplate; $('#previewBox').style.setProperty('--brand-preview',$('#brandColor').value||'#d97706'); }
function selectPackage(code){selectedPackage=code;localStorage.setItem('webumkm_package',code);document.querySelectorAll('.package').forEach(el=>el.classList.toggle('active',el.dataset.package===code));}
function selectTemplate(id){selectedTemplate=id;localStorage.setItem('webumkm_template',id);document.querySelectorAll('.template-card').forEach(el=>el.classList.toggle('selected',el.dataset.template===id));sync();}
fields.forEach(id=>$('#'+id).addEventListener('input',sync));
document.querySelectorAll('.package').forEach(el=>el.addEventListener('click',()=>selectPackage(el.dataset.package)));
document.querySelectorAll('.template-card').forEach(el=>el.addEventListener('click',()=>selectTemplate(el.dataset.template)));
function collect(){return{name:$('#businessName').value,tagline:$('#tagline').value,description:$('#description').value,whatsapp:$('#whatsapp').value,city:$('#city').value,address:$('#address').value,aboutTitle:$('#aboutTitle').value,aboutText:$('#aboutText').value,ctaTitle:$('#ctaTitle').value,product1:$('#product1').value,product2:$('#product2').value,product3:$('#product3').value,brandColor:$('#brandColor').value,logo:$('#logo').value,heroImage:$('#heroImage').value,productImage1:$('#productImage1').value,productImage2:$('#productImage2').value,productImage3:$('#productImage3').value};}
$('#saveBtn').addEventListener('click',()=>{localStorage.setItem('webumkm_data',JSON.stringify(collect()));$('#saveStatus').textContent='✓ Data, branding, dan gambar berhasil disimpan di browser.';sync()});
$('#previewBtn').addEventListener('click',()=>window.open(`../sites/${currentSlug()}`,'_blank'));
$('#publishBtn').addEventListener('click',async()=>{const slug=slugify($('#businessName').value);if(!$('#businessName').value.trim()){ $('#saveStatus').textContent='⚠ Nama usaha wajib diisi.';return;}if(!/^#[0-9a-fA-F]{6}$/.test($('#brandColor').value)){ $('#saveStatus').textContent='⚠ Warna utama tidak valid.';return;}$('#saveStatus').textContent='⏳ Membuat website...';const payload={businessName:$('#businessName').value,tagline:$('#tagline').value,description:$('#description').value,whatsapp:$('#whatsapp').value,city:$('#city').value,address:$('#address').value,slug,templateId:selectedTemplate,packageCode:selectedPackage,content:content()};try{const response=await fetch('../api/sites',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Gagal membuat website');localStorage.setItem('webumkm_site_slug',data.slug);$('#saveStatus').textContent=`✓ Website aktif: ${data.url}`;await loadSites();await loadOrders();window.open(data.url,'_blank')}catch(error){localStorage.setItem('webumkm_site_slug',slug);$('#saveStatus').textContent=`⚠ ${error.message}. Pastikan D1 sudah terhubung.`}});
async function loadSites(){try{const r=await fetch('../api/sites');const d=await r.json();const sites=d.sites||[];$('#siteCount').textContent=sites.length;$('#sitesList').innerHTML=sites.length?sites.map(s=>`<div class="site-row"><div><strong>${escapeHtml(s.business_name)}</strong><small>${escapeHtml(s.slug)} · ${templateNames[s.template_id]||s.template_id||'Template'} · ${s.package_code||'-'}</small></div><a href="../sites/${encodeURIComponent(s.slug)}" target="_blank">Buka →</a></div>`).join(''):'<div class="empty">Belum ada website dari database.</div>'}catch(e){$('#siteCount').textContent='0'}}
async function loadOrders(){const slug=currentSlug();if(!slug||slug==='website-umkm')return;try{const r=await fetch(`../api/orders?slug=${encodeURIComponent(slug)}`);const d=await r.json();const orders=d.orders||[];$('#orderCount').textContent=orders.length;$('#ordersList').innerHTML=orders.length?orders.map(o=>{const pay=o.payment_url?`<a href="${escapeAttr(o.payment_url)}" target="_blank" rel="noopener">Bayar sekarang →</a>`:'<span>Menunggu gateway</span>';return `<div class="site-row"><div><strong>${escapeHtml(packageNames[o.package_code]||o.package_code)} · Rp${Number(o.amount||0).toLocaleString('id-ID')}</strong><small>${escapeHtml(o.id)} · ${escapeHtml(o.status)} · ${escapeHtml(o.customer_name||'Pelanggan')}</small></div><div>${pay}</div></div>`}).join(''):'<div class="empty">Belum ada pesanan untuk website ini.</div>'}catch(e){$('#ordersList').innerHTML='<div class="empty">Pesanan belum dapat dimuat.</div>'}}
async function loadReferral(){const code=localStorage.getItem('webumkm_referral_code');if(!code){$('#referralReward').textContent='Rp0';return;}try{const r=await fetch(`../api/referrals?code=${encodeURIComponent(code)}`);const d=await r.json();$('#referralReward').textContent=`Rp${Number(d.reward||0).toLocaleString('id-ID')}`}catch(e){$('#referralReward').textContent='Rp0'}}
function escapeHtml(v){return String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function escapeAttr(v){return escapeHtml(v).replace(/`/g,'&#96;');}
const saved=localStorage.getItem('webumkm_data');if(saved){try{const d=JSON.parse(saved);Object.keys(d).forEach(k=>{const el=$('#'+k);if(el)el.value=d[k]||''});}catch(e){}}
selectPackage(selectedPackage);selectTemplate(selectedTemplate);sync();loadSites();loadOrders();loadReferral();